---
title: "Report of the 2022 EUR Open Science Survey"
author: '[Dr. Lizette Guzman-Ramirez](https://www.linkedin.com/in/drlizguzman/), [Dr. Antonio Schettino](https://antonio-schettino.com/)'
date: 2022-05-26
output:
  bookdown::html_document2:
    # # appearance
    # # table of content
    # # code
    # # figures
    theme: flatly
    highlight: tango
    toc: true
    toc_float: true  
    number_sections: false
    # code_folding: true
    fig_width: 8
    fig_height: 8
    fig_caption: true
editor_options: 
  chunk_output_type: console
---

```{r doc-setup, include = FALSE}

# RNG
seed_proj <- 52118 # A1Z26 cipher (https://www.boxentriq.com/code-breaking/letters-to-numbers)
set.seed(seed_proj)

### install packages
# install.packages("bookdown")
# install.packages("knitr")
# install.packages("kableExtra")
# install.packages("here")
# install.packages("tidyverse")

### load packages
library(bookdown)
library(knitr)
library(kableExtra)
library(here)
library(tidyverse)

# RMarkdown
options(digits = 2) # number of decimal digits
opts_chunk$set(
  echo = FALSE, # do not show code
  warning = FALSE, # no package warnings
  message = FALSE # no package messages
)

# custom function for tables
kable_custom <- function(data, caption) {
  knitr::kable(data, digits = getOption("digits"), caption = caption) %>%
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
}

```

***
***

# Introduction

<!-- The Erasmus Research Institute of Management (ERIM) is committed to making Open Science practices the norm among its researchers. -->

<!-- Open Science increases transparency throughout the research cycle -- from hypothesis, methodology, observation, data collection, to analysis and publication --, resulting in increased research efficiency and enhanced research quality, visibility, and engagement. Open Science also enables the creation of new research questions and promotes collaborations and community building. -->

<!-- For these reasons, ERIM wanted to have a baseline on what and how much open science practices its researchers are already engaging with and which ones they want to learn more about. These questions created the need to conduct a survey. -->

<!-- The ESE and RSM Open Science Spring Survey was open to all researchers from the 6th of April to the 6th of May 2021. Questions were adapted from the [Swinburne Open Science Survey](https://osf.io/vpwf7/). -->

<!-- The survey explored how researchers perceive and use open science practices. Eight main topics were covered: -->

<!-- 1. Preregistration -->
<!-- 2. Open materials/code -->
<!-- 3. Open data -->
<!-- 4. Pre-publication archiving -->
<!-- 5. Open access -->
<!-- 6. General experience with open science practices -->
<!-- 7. Awareness of available tools -->
<!-- 8. Role of ERIM -->

<!-- This report displays the combined results (ESE and RSM) as well as separately for each school[^1]. -->

<!-- This is a living document that will be updated with new information and insights. For any comments or questions, please contact [Dr. Lizette Guzman-Ramirez](mailto:guzmanramirez@rsm.nl) (ERIM Research Data Steward) or [Dr. Antonio Schettino](mailto:schettino@eur.nl) (ERS Open Science Coordinator). -->

```{r load-clean-data}

EUR_OS <-
  read_csv(
    here("data", "preproc", "CLEAN_OS_Survey_responses.csv"),
    col_types = c("flffccccccccc")
    )

```

# Respondents

```{r complete-questionnaires-data}

# percentage of (in)complete surveys
EUR_OS_incomplete <-
  EUR_OS %>% 
  group_by(participant) %>%
  summarize(survey = length(which(Finished == TRUE))/length(Finished)) %>%
  ungroup() %>%
  count(survey) %>% 
  mutate(
    survey = ifelse(survey == 1, "complete", "incomplete"),
    perc = round(n / sum(n) * 100, 2), # calculate percentage
    lab_perc = paste(round(n / sum(n) * 100, 2), "%", sep = "") # percentage as text (for plot labels)
  )

```

A total of `r sum(EUR_OS_incomplete$n)` respondents started the survey, and `r pull(filter(EUR_OS_incomplete, survey == "complete"), n)` completed it. An overview of response rate per school can be found in Table \@ref(tab:table1).

(ref:table1) Response rate per school.

(ref:table1-footnote) NA indicates no response.

```{r table1}

EUR_OS_incomplete_school <-
  EUR_OS %>% 
  filter(question == "School") %>% 
  select_if(~ sum(!is.na(.)) > 0) %>%
  pivot_wider(
    id_cols = c(participant, Finished),
    names_from = question,
    values_from = value_1
  ) %>% 
  mutate(
    School = gsub("Other_.*", "Other", School), # group all other responses in "Other"
    School = recode( # use school abbreviations, for better readability
      factor(School),
      "Erasmus School of History, Culture and Communication (ESHCC)" = "ESHCC",
      "Erasmus School of Health Policy & Management (ESHPM)" = "ESHPM",
      "Erasmus School of Philosophy (ESPHIL)" = "ESPhil",
      "Erasmus School of Social and Behavioural Sciences (ESSB)" = "ESSB",
      "Erasmus School of Law (ESL)" = "ESL",
      "International Institute of Social Studies (ISS)" = "ISS"
    )
  ) %>%
  group_by(School) %>%
  summarize(
    n = n(),
    perc = round(length(which(Finished == TRUE))/length(Finished) * 100, 2),
    lab_perc = paste(perc, "%", sep = "")
  )

# table
EUR_OS_incomplete_school %>%
  select(-perc) %>% 
  rename("completed survey" = lab_perc) %>% 
  kable_custom(caption = "(ref:table1)") %>% 
  footnote(
    general = "(ref:table1-footnote)",
    footnote_as_chunk = TRUE
  )

```




